<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign in to GoogleSave your passwords securely with your Google AccountStay signed outSign in</name>
   <tag></tag>
   <elementGuidId>c8227017-e0da-449e-a637-cf10f2321205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.WrcADd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.WrcADd</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f253f093-6adc-4d17-b96a-a7c584421b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WrcADd</value>
      <webElementGuid>bf616269-77ca-4b2f-9184-78c3171da324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in to GoogleSave your passwords securely with your Google AccountStay signed outSign in</value>
      <webElementGuid>91bf5fa6-df39-497d-bc4f-50d2b500a2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;SSPGKf&quot;]/div[@class=&quot;T4LgNb eejsDc&quot;]/div[@class=&quot;kFwPee&quot;]/c-wiz[1]/div[@class=&quot;WrcADd&quot;]</value>
      <webElementGuid>dbe5c370-e7e6-448c-838e-7bcd7a7048b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/test/Page_Google/iframe_Sign in_callout</value>
      <webElementGuid>49a59a93-5702-4df8-af88-62e76c94ad0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yDmH0d']/c-wiz/div/div/c-wiz/div</value>
      <webElementGuid>6aa65cd8-05d2-4d48-989f-9bdc225485b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/c-wiz/div</value>
      <webElementGuid>e91dae86-fc38-47f6-9b6d-af2071de154a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sign in to GoogleSave your passwords securely with your Google AccountStay signed outSign in' or . = 'Sign in to GoogleSave your passwords securely with your Google AccountStay signed outSign in')]</value>
      <webElementGuid>9cc0163a-0e31-431a-9f25-3aedc4b8d4a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
