name: Run Katalon Tests

on:
  push:
    branches:
      - main # Trigger the workflow when changes are pushed to the main branch
  pull_request: # Optionally, trigger the workflow for pull requests

jobs:
  katalon-tests:
    runs-on: ubuntu-latest # GitHub Actions runner environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (Katalon requires Java)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Specify the Java version required for Katalon

      # Step 3: Download Katalon Runtime Engine
      - name: Download Katalon Runtime Engine
        run: |
          curl -O https://download.katalon.com/x.x.x/Katalon_Studio_Engine_Linux_x64-x.x.x.tar.gz
          tar -xzf Katalon_Studio_Engine_Linux_x64-x.x.x.tar.gz

      # Step 4: Execute Katalon Tests
      - name: Run Katalon Test Suite
        run: |
          ./katalonc -noSplash -runMode=console -projectPath=$(pwd)/path/to/your/project.prj \
          -testSuitePath="Test Suites/YourTestSuite" \
          -reportFolder="Reports" \
          -reportFileName="report" \
          -apiKey=your_katalon_api_key
